name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/keyfile
          chmod 600 /tmp/keyfile
          mkdir -p $HOME/.ssh
          cp known_hosts $HOME/.ssh/known_hosts

          ls -l /tmp/keyfile
          ls -l $HOME/.ssh

          ssh -i /tmp/keyfile ubuntu@51.20.134.255 "sudo bash ~/CI-CD-AWS-/part-2-scripts/deploy.sh"
